name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize
  push:

jobs:
  CI:
    uses: Arvernus/PlatformIOGithubActions/.github/workflows/iRockProjectCI.yaml@main
    secrets:
      PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
